"""'initial'

Revision ID: acb5e99a4eee
Revises:
Create Date: 2024-03-01 02:31:20.983227

"""
from typing import Sequence, Union
import zoneinfo

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb5e99a4eee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminLog',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('admin', sa.String(length=32), nullable=True),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=252), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('AdminSavedPositions',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('admin', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('GangZone',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('gang_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('min_x', sa.Float(), nullable=True),
    sa.Column('min_y', sa.Float(), nullable=True),
    sa.Column('max_x', sa.Float(), nullable=True),
    sa.Column('max_y', sa.Float(), nullable=True),
    sa.Column('gang_atk_id', sa.Integer(), nullable=True),
    sa.Column('gang_def_id', sa.Integer(), nullable=True),
    sa.Column('gang_atk_score', sa.Integer(), nullable=True),
    sa.Column('gang_def_score', sa.Integer(), nullable=True),
    sa.Column('capture_time', sa.Integer(), nullable=True),
    sa.Column('capture_cooldown', sa.Integer(), nullable=True),
    sa.Column('is_capture', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('House',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('interior_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('Player',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('pin', sa.String(length=6), nullable=True),
    sa.Column('registration_ip', sa.String(length=32), nullable=True),
    sa.Column('last_ip', sa.String(length=32), nullable=True),
    sa.Column('registration_data', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='Europe/Moscow')), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('donate', sa.Integer(), nullable=True),
    sa.Column('dm_rating', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('heals', sa.Integer(), nullable=True),
    sa.Column('masks', sa.Integer(), nullable=True),
    sa.Column('gang_id', sa.Integer(), nullable=True),
    sa.Column('vip_level', sa.Integer(), nullable=True),
    sa.Column('admin_level', sa.Integer(), nullable=True),
    sa.Column('vip_gangwar_template', sa.String(length=16), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('is_jailed', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('jail_time', sa.Integer(), nullable=True),
    sa.Column('mute_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('PlayerFreeroamGunSlots',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('slot_melee', sa.Integer(), nullable=True),
    sa.Column('slot_pistol', sa.Integer(), nullable=True),
    sa.Column('slot_shotgun', sa.Integer(), nullable=True),
    sa.Column('slot_machine_gun', sa.Integer(), nullable=True),
    sa.Column('slot_assault_rifle', sa.Integer(), nullable=True),
    sa.Column('slot_long_rifle', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('PlayerSettings',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('disabled_ping_td', sa.Boolean(), nullable=True),
    sa.Column('disabled_global_chat_gw', sa.Boolean(), nullable=True),
    sa.Column('spawn_in_house', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('ServerAnalytics',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('date', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='Europe/Moscow')), nullable=True),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('Vehicle',
    sa.Column('uid', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('engine', sa.Integer(), nullable=True),
    sa.Column('lights', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('color1', sa.Integer(), nullable=True),
    sa.Column('color2', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('virtual_world', sa.Integer(), nullable=True),
    sa.Column('add_siren', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vehicle')
    op.drop_table('ServerAnalytics')
    op.drop_table('PlayerSettings')
    op.drop_table('PlayerFreeroamGunSlots')
    op.drop_table('Player')
    op.drop_table('House')
    op.drop_table('GangZone')
    op.drop_table('AdminSavedPositions')
    op.drop_table('AdminLog')
    # ### end Alembic commands ###
